In [5]:
#Dependencies
import numpy as np
import pandas as pd
from PIL import Image, ImageSequence
from pdf2image import convert_from_path, pdfinfo_from_path
import logging as logger
import os
import re
import pytesseract
import bs4

In [6]:
#Configs
raw_folder = "/Users/sali115/text_mapping/data/raw"
doc_name = "Exclusions - non-VIP 5.2.pdf"
file_name = os.path.join(raw_folder, doc_name)
processed_folder = "/Users/sali115/text_mapping/data/processed"

In [7]:
#Utils

def rename_images(image_path, folder_path):
    try:
        page_num = int(re.findall(r"(\d+)\.[a-z]{3}$", image_path)[0])
        new_path = os.path.join(folder_path, f"page{page_num}.png")
        os.rename(image_path, new_path)
        doc_name = folder_path.rstrip("/").split("/")[-1]
        logger.info(f"Saved Image Number {page_num} of {doc_name} at {new_path}")
    except Exception as e:
        logger.error(f"Error in renaming image: {e}")
        
def ocr_hocr(img_path, psm=4):
    return pytesseract.image_to_pdf_or_hocr(
        img_path, extension="hocr", config=f"--psm {psm}"
    )

def get_text_from_hocr(hocr):
    hocr_text = []
    soup = bs4.BeautifulSoup(hocr, "html.parser")
    for line in soup.select(".ocr_line"):
        line_text = re.sub(r"\s+", " ", line.text).strip()
        alphanum_text = re.sub("[^a-zA-Z0-9 \n]", "", line_text).strip()
        if alphanum_text != "":
            hocr_text.append(line_text)
    return "\n".join(hocr_text)

def get_ocr_df(page_num, hocr):
    page_dict = {
        "page": '$page_num',
        "line": '$line',
        "text": '$text',
    }
    line = 1
    text = get_text_from_hocr(hocr).split(".")
    text = [re.sub(r"\n\d+", "", txt).replace("\n", " ") for txt in text]
    text = list(filter(None, text))
    
    page_record = list()
    
    for txt in text:
        if txt.isdigit():
            continue
        line += 1
        page_dict["page"] = page_num
        page_dict["line"] = line
        page_dict["text"] = txt
        page_record.append(page_dict.copy())
    return pd.DataFrame.from_records(page_record)

In [186]:
# # def fltr(txt):
# #     return re.sub(r"\\n[\d+]", " ", txt)
# list(filter(lambda x: re.sub(r"\n\d+", " ", x),text))

In [187]:
# text

In [188]:
# text = get_text_from_hocr(hocr).split(".")
# text = [re.sub(r"\n\d+", "", txt) for txt in text]
# text = list(filter(None, text))
# text

In [189]:
# list(filter(None, text))

In [190]:
# get_text_from_hocr(hocr)

In [4]:
#File Splitting - Doc pre-processing

logger.info(f"Splitting pdf {doc_name} into PNGs")
output_folder = os.path.join(processed_folder, doc_name.split(".")[0])
os.makedirs(output_folder, exist_ok=True)
num_pages = pdfinfo_from_path(file_name)['Pages']
logger.info(
    f"Found {num_pages} pages of {doc_name} to split into PNGs")

image_paths = convert_from_path(file_name,
                                output_folder=output_folder,
                                paths_only=True,
                                fmt="png",
                                output_file="page")
for image_path in image_paths:
    rename_images(image_path, output_folder)

In [9]:
output_folder = os.path.join(processed_folder, doc_name.split(".")[0])

In [10]:
#Getting OCR Results
ocr_df = pd.DataFrame(columns= ["page","line","text", "CODE"])

for page_path in os.listdir(output_folder):
    page_num = int(re.findall(r'\d+', page_path)[0])
    page_img = os.path.join(output_folder, page_path)
    hocr = ocr_hocr(page_img).decode(encoding="utf-8", errors="ignore")
    ocr_df = pd.concat([ocr_df, get_ocr_df(page_num, hocr)])

In [11]:
ocr_df.head()

  page line                                               text CODE
0    9    2  Any expenses related to immunomodulators and i...  NaN
1    9    3   Any expenses related to the treatment of slee...  NaN
2    9    4    Services and educational programs for handicaps  NaN
3    9    5                                                  A  NaN
4    9    6   Injuries or illnesses suffered by the Insured...  NaN

In [12]:
cpt_df=pd.read_excel("/Users/sali115/text_mapping/data/helper/CPT CODES.xlsx")
cpt_df.head()

,CPT_CODE,SHORT_DESCRIPTION,LONG_DESCRIPTION,FULL_DESCRIPTION
0,0001F,HEART FAILURE COMPOSITE,HRT FAILURE ASSESSED,Heart failure assessed (includes assessment of...
1,0005F,OSTEOARTHRITIS COMPOSITE,OSTEOARTHRITIS COMPOSITE,Osteoarthritis assessed (OA) Includes assessme...
2,00100,ANESTH SALIVARY GLAND,ANESTHESIA SALIVARY GLANDS WITH BIOPSY,"Anesthesia for procedures on salivary glands, ..."
3,00102,ANESTH REPAIR OF CLEFT LIP,ANESTHESIA CLEFT LIP INVOLVING PLASTIC REPAIR,Anesthesia for procedures involving plastic re...
4,00103,ANESTH BLEPHAROPLASTY,ANESTHESIA EYELID RECONSTRUCTIVE PROCEDURE,Anesthesia for reconstructive procedures of ey...

In [13]:
from transformers import BertTokenizer, BertModel, AutoTokenizer, AutoModel

In [14]:
tokenizer = AutoTokenizer.from_pretrained("emilyalsentzer/Bio_ClinicalBERT")
model = AutoModel.from_pretrained("emilyalsentzer/Bio_ClinicalBERT")

Some weights of the model checkpoint at emilyalsentzer/Bio_ClinicalBERT were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [15]:
import torch

In [16]:
input_ids = torch.tensor(tokenizer.encode(cpt_df["FULL_DESCRIPTION"].values[0])).unsqueeze(0)

In [17]:
outputs = model(input_ids)

In [18]:
embeddings_of_last_layer=outputs[0]
cls_embeddings=embeddings_of_last_layer[0][0]

In [19]:
len(cls_embeddings)

768

In [20]:
page_2_df = ocr_df[ocr_df.page == 2]
page_2_df

   page line                                               text CODE
0     2    2            Emirate of Abu Dhabi Non-VIP Exclusions  NaN
1     2    3   Healthcare Services, which are not medically ...  NaN
2     2    4   All expenses relating to dental treatment, de...  NaN
3     2    5   Domiciliary care; private nursing care; care ...  NaN
4     2    6                          Custodial care includes a  NaN
5     2    7               Non-medical treatment services; or b  NaN
6     2    8   Health-related services which do not seek to ...  NaN
7     2    9   Services which do not require continuous admi...  NaN
8     2   10   Personal comfort and convenience items (telev...  NaN
9     2   11   Healthcare Services and associated expenses f...  NaN
10    2   12   Cosmetic operations which improve physical ap...  NaN
11    2   13   Breast reconstruction following a mastectomy ...  NaN
12    2   14   Surgical and non-surgical treatment for obesi...  NaN
13    2   15   Medically — non-approved experimental, resear...  NaN

In [21]:
page_2_df=page_2_df.drop(0)
page_2_df

   page line                                               text CODE
1     2    3   Healthcare Services, which are not medically ...  NaN
2     2    4   All expenses relating to dental treatment, de...  NaN
3     2    5   Domiciliary care; private nursing care; care ...  NaN
4     2    6                          Custodial care includes a  NaN
5     2    7               Non-medical treatment services; or b  NaN
6     2    8   Health-related services which do not seek to ...  NaN
7     2    9   Services which do not require continuous admi...  NaN
8     2   10   Personal comfort and convenience items (telev...  NaN
9     2   11   Healthcare Services and associated expenses f...  NaN
10    2   12   Cosmetic operations which improve physical ap...  NaN
11    2   13   Breast reconstruction following a mastectomy ...  NaN
12    2   14   Surgical and non-surgical treatment for obesi...  NaN
13    2   15   Medically — non-approved experimental, resear...  NaN

In [22]:
def ClinicalBert_embeddings(text):
    
    input_ids = torch.tensor(tokenizer.encode(text)).unsqueeze(0)
    outputs = model(input_ids)
    embeddings_of_last_layer = outputs[0]
    cls_embeddings = embeddings_of_last_layer[0][0]
    
    return cls_embeddings

In [23]:
# cpt_embeddings= dict()
# for _,row in cpt_df.iterrows():
#     embeddings = ClinicalBert_embeddings(row["FULL_DESCRIPTION"])
#     cpt_embeddings[row["CPT_CODE"]] = embeddings

In [24]:
# !pip install sklearn

In [25]:
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
import pickle

In [29]:
# infile=open("/Users/pdas59/Downloads/1.pickle","rb")
# emb_dict=pickle.load(infile)
# infile.close()

In [30]:
# top_dict=dict()

In [31]:
# code=[]
# for _,row in page_2_df.iterrows():
#     sim_dict=dict()
#     cls_emb=ClinicalBert_embeddings(row["text"])
#     for i in emb_dict:
#         s=cosine_similarity(cls_emb.detach().numpy().reshape(1,-1),emb_dict[i].detach().numpy().reshape(1,-1))[0][0]
#         sim_dict[i]=s
#     code.append(list(sorted(sim_dict.items(),key=lambda x:x[1]))[-1])

In [32]:
# code

In [27]:
new_df=ocr_df[~ocr_df.page.isin([1,10])]
new_df

   page line                                               text CODE
0     9    2  Any expenses related to immunomodulators and i...  NaN
1     9    3   Any expenses related to the treatment of slee...  NaN
2     9    4    Services and educational programs for handicaps  NaN
3     9    5                                                  A  NaN
4     9    6   Injuries or illnesses suffered by the Insured...  NaN
..  ...  ...                                                ...  ...
9     2   11   Healthcare Services and associated expenses f...  NaN
10    2   12   Cosmetic operations which improve physical ap...  NaN
11    2   13   Breast reconstruction following a mastectomy ...  NaN
12    2   14   Surgical and non-surgical treatment for obesi...  NaN
13    2   15   Medically — non-approved experimental, resear...  NaN

[203 rows x 4 columns]

In [28]:
new_df1 = new_df[~(new_df.text.str.contains("Non-VIP") | new_df.text.str.contains("Pharmacy Exclusions"))]

In [36]:
# code=[]
# for _,row in new_df1.iterrows():
#     sim_dict=dict()
#     cls_emb=ClinicalBert_embeddings(row["text"])
#     for i in emb_dict:
#         s=cosine_similarity(cls_emb.detach().numpy().reshape(1,-1),emb_dict[i].detach().numpy().reshape(1,-1))[0][0]
#         sim_dict[i]=s
#     code.append(list(sorted(sim_dict.items(),key=lambda x:x[1]))[-1])

In [37]:
# len(code)

In [35]:
new_df1

   page line                                               text CODE
0     9    2  Any expenses related to immunomodulators and i...  NaN
1     9    3   Any expenses related to the treatment of slee...  NaN
2     9    4    Services and educational programs for handicaps  NaN
3     9    5                                                  A  NaN
4     9    6   Injuries or illnesses suffered by the Insured...  NaN
..  ...  ...                                                ...  ...
9     2   11   Healthcare Services and associated expenses f...  NaN
10    2   12   Cosmetic operations which improve physical ap...  NaN
11    2   13   Breast reconstruction following a mastectomy ...  NaN
12    2   14   Surgical and non-surgical treatment for obesi...  NaN
13    2   15   Medically — non-approved experimental, resear...  NaN

[199 rows x 4 columns]

In [29]:
overall_code=[]
for file_name in os.listdir("/Users/sali115/text_mapping/data/processed/pickle"):
    infile=open(os.path.join("/Users/sali115/text_mapping/data/processed/pickle",file_name),"rb")
    pkl_dict=pickle.load(infile)
    infile.close()
    code=[]
    for _,row in new_df1.iterrows():
        sim_dict=dict()
        cls_emb=ClinicalBert_embeddings(row["text"])
        for i in pkl_dict:
            s=cosine_similarity(cls_emb.detach().numpy().reshape(1,-1),pkl_dict[i].detach().numpy().reshape(1,-1))[0][0]
            sim_dict[i]=s
        code.append(list(sorted(sim_dict.items(),key=lambda x:x[1]))[-1])
    overall_code.append(code)

In [34]:
sim_dict

{'73030': 0.71515155,
 '73040': 0.76858157,
 '73050': 0.7675899,
 '73060': 0.72997016,
 '73070': 0.7105893,
 '73080': 0.7272713,
 '73085': 0.77351654,
 '73090': 0.69786316,
 '73092': 0.75083447,
 '73100': 0.7022052,
 '73110': 0.7200954,
 '73115': 0.77507746,
 '73120': 0.7020019,
 '73130': 0.72069526,
 '73140': 0.7487508,
 '73200': 0.76089895,
 '73201': 0.7621031,
 '73202': 0.7645806,
 '73206': 0.79179114,
 '73218': 0.7608068,
 '73219': 0.7577073,
 '73220': 0.7740932,
 '73221': 0.7552671,
 '73222': 0.7578173,
 '73223': 0.7760589,
 '73225': 0.76937556,
 '73501': 0.7068284,
 '73502': 0.7466437,
 '73503': 0.73154783,
 '73521': 0.7184992,
 '73522': 0.74625057,
 '73523': 0.7393962,
 '73525': 0.7721214,
 '73551': 0.6763139,
 '73552': 0.7118989,
 '73560': 0.7199042,
 '73562': 0.69641805,
 '73564': 0.7379331,
 '73565': 0.73862743,
 '73580': 0.7630634,
 '73590': 0.69222814,
 '73592': 0.7506412,
 '73600': 0.70067894,
 '73610': 0.7167757,
 '73615': 0.7715854,
 '73620': 0.7004035,
 '73630': 0.7214031,
 '73650': 0.7347062,
 '73660': 0.73577756,
 '73700': 0.7594622,
 '73701': 0.7617923,
 '73702': 0.76501936,
 '73706': 0.79152083,
 '73718': 0.75704306,
 '73719': 0.7546772,
 '73720': 0.77296394,
 '73721': 0.7676101,
 '73722': 0.7571827,
 '73723': 0.77606225,
 '73725': 0.77118826,
 '74018': 0.68804437,
 '74019': 0.7077505,
 '74021': 0.73800087,
 '74022': 0.775614,
 '74150': 0.7637476,
 '74160': 0.7656929,
 '74170': 0.7694203,
 '74174': 0.79137313,
 '74175': 0.7947595,
 '74176': 0.7552503,
 '74177': 0.7599844,
 '74178': 0.76681995,
 '74181': 0.76606077,
 '74182': 0.76453054,
 '74183': 0.7696075,
 '74185': 0.75385976,
 '74190': 0.7944884,
 '74210': 0.7672477,
 '74220': 0.7424441,
 '74230': 0.78484833,
 '74235': 0.7821231,
 '74240': 0.7611856,
 '74241': 0.7550623,
 '74245': 0.7634908,
 '74246': 0.7452181,
 '74247': 0.7327771,
 '74249': 0.74534804,
 '74250': 0.7696492,
 '74251': 0.75039023,
 '74260': 0.79292774,
 '74261': 0.77283084,
 '74262': 0.7782444,
 '74263': 0.8058297,
 '74270': 0.7822472,
 '74280': 0.7712047,
 '74283': 0.8006291,
 '74290': 0.8008181,
 '74300': 0.7452235,
 '74301': 0.8145547,
 '74328': 0.7575063,
 '74329': 0.7529386,
 '74330': 0.79622424,
 '74340': 0.7955773,
 '74355': 0.7466363,
 '74360': 0.7483835,
 '74363': 0.74232835,
 '74400': 0.7868005,
 '74410': 0.8342365,
 '74415': 0.8031004,
 '74420': 0.7905174,
 '74425': 0.80495226,
 '74430': 0.7401364,
 '74440': 0.7494639,
 '74445': 0.773438,
 '74450': 0.7704406,
 '74455': 0.82670796,
 '74470': 0.7844446,
 '74485': 0.7363042,
 '74710': 0.78933537,
 '74712': 0.75597477,
 '74713': 0.82123554,
 '74740': 0.8018021,
 '74742': 0.78041255,
 '74775': 0.81953704,
 '75557': 0.75860167,
 '75559': 0.7762571,
 '75561': 0.7752234,
 '75563': 0.7806561,
 '75565': 0.8136234,
 '75571': 0.7728473,
 '75572': 0.80148214,
 '75573': 0.80692405,
 '75574': 0.7869919,
 '75600': 0.76437414,
 '75605': 0.76961684,
 '75625': 0.77372646,
 '75630': 0.7693825,
 '75635': 0.7856162,
 '75705': 0.76901025,
 '75710': 0.74001056,
 '75716': 0.74201316,
 '75726': 0.7513049,
 '75731': 0.7500582,
 '75733': 0.76284075,
 '75736': 0.75075364,
 '75741': 0.75599945,
 '75743': 0.75263435,
 '75746': 0.7465646,
 '75756': 0.72422874,
 '75774': 0.8051181,
 '75801': 0.7684668,
 '75803': 0.77399606,
 '75805': 0.75027883,
 '75807': 0.75224835,
 '75809': 0.7744336,
 '75810': 0.7844664,
 '75820': 0.7526967,
 '75822': 0.758507,
 '75825': 0.75734067,
 '75827': 0.7554883,
 '75831': 0.76466006,
 '75833': 0.76749396,
 '75840': 0.7565898,
 '75842': 0.76661485,
 '75860': 0.7652347,
 '75870': 0.70571005,
 '75872': 0.7323578,
 '75880': 0.77321625,
 '75885': 0.7804721,
 '75887': 0.75346065,
 '75889': 0.7748296,
 '75891': 0.7405664,
 '75893': 0.80514324,
 '75894': 0.7979946,
 '75898': 0.81368697,
 '75901': 0.76368904,
 '75902': 0.74845946,
 '75956': 0.7903291,
 '75957': 0.78792554,
 '75958': 0.80002475,
 '75959': 0.7799018,
 '75970': 0.77810264,
 '75984': 0.7981838,
 '75989': 0.795532,
 '76000': 0.80910105,
 '76001': 0.82224476,
 '76010': 0.7177614,
 '76080': 0.7523825,
 '76098': 0.7410869,
 '76100': 0.7718203,
 '76101': 0.752741,
 '76102': 0.7638117,
 '76120': 0.7910272,
 '76125': 0.7950048,
 '76140': 0.74442047,
 '76376': 0.78456104,
 '76377': 0.781958,
 '76380': 0.76860774,
 '76390': 0.751392,
 '76496': 0.7999851,
 '76497': 0.77299887,
 '76498': 0.7828849,
 '76499': 0.7785202,
 '76506': 0.8006216,
 '76510': 0.7625392,
 '76511': 0.8018172,
 '76512': 0.8150018,
 '76513': 0.8116993,
 '76514': 0.8121646,
 '76516': 0.78546184,
 '76519': 0.7935666,
 '76529': 0.7709273,
 '76536': 0.77875507,
 '76604': 0.77709216,
 '76641': 0.68739593,
 '76642': 0.7113314,
 '76700': 0.66571045,
 '76705': 0.7677465,
 '76706': 0.7358979,
 '76770': 0.7128212,
 '76775': 0.7113419,
 '76776': 0.7588396,
 '76800': 0.75462055,
 '76801': 0.7437298,
 '76802': 0.7795679,
 '76805': 0.74804443,
 '76810': 0.78821266,
 '76811': 0.7363152,
 '76812': 0.7673473,
 '76813': 0.7440479,
 '76814': 0.77974516,
 '76815': 0.73746145,
 '76816': 0.769171,
 '76817': 0.6770275,
 '76818': 0.79206574,
 '76819': 0.79267824,
 '76820': 0.78925633,
 '76821': 0.78690773,
 '76825': 0.79054534,
 '76826': 0.7997161,
 '76827': 0.758366,
 '76828': 0.79649127,
 '76830': 0.7156956,
 '76831': 0.7675597,
 '76856': 0.6845614,
 '76857': 0.73638123,
 '76870': 0.7701788,
 '76872': 0.7148136,
 '76873': 0.7461213,
 '76881': 0.760015,
 '76882': 0.771222,
 '76885': 0.8037197,
 '76886': 0.7937547,
 '76930': 0.75935745,
 '76932': 0.77497023,
 '76936': 0.80557066,
 '76937': 0.78877896,
 '76940': 0.78835016,
 '76941': 0.7853478,
 '76942': 0.8060473,
 '76945': 0.77540153,
 '76946': 0.75110924,
 '76948': 0.7738888,
 '76965': 0.7895098,
 '76970': 0.6890252,
 '76975': 0.77475107,
 '76977': 0.8173333,
 '76998': 0.7369695,
 '76999': 0.80871016,
 '77001': 0.81247634,
 '77002': 0.81850076,
 '77003': 0.8096645,
 '77011': 0.7687895,
 '77012': 0.8019627,
 '77013': 0.79437643,
 '77014': 0.7895667,
 '77021': 0.7863698,
 '77022': 0.7986302,
 '77053': 0.79256046,
 '77054': 0.78743505,
 '77058': 0.75606406,
 '77059': 0.7598703,
 '77061': 0.7233982,
 '77062': 0.729676,
 '77063': 0.78600854,
 '77065': 0.75776076,
 '77066': 0.77079797,
 '77067': 0.78482866,
 '77071': 0.8159039,
 '77072': 0.79640925,
 '77073': 0.794264,
 '77074': 0.7529247,
 '77075': 0.7210772,
 '77076': 0.7362185,
 '77077': 0.73308736,
 '77078': 0.77600867,
 '77080': 0.8073247,
 '77081': 0.8117614,
 '77084': 0.7849985,
 '77085': 0.81156033,
 '77086': 0.78945374,
 '77261': 0.8050147,
 '77262': 0.7694614,
 '77263': 0.8001263,
 '77280': 0.79560405,
 '77285': 0.7417786,
 '77290': 0.77996933,
 '77293': 0.81807065,
 '77295': 0.8255571,
 '77299': 0.80323714,
 '77300': 0.8280431,
 '77301': 0.8047423,
 '77306': 0.8194159,
 '77307': 0.80997163,
 '77316': 0.7796695,
 '77317': 0.77463835,
 '77318': 0.7794267,
 '77321': 0.77257407,
 '77331': 0.7802829,
 '77332': 0.82957053,
 '77333': 0.81956124,
 '77334': 0.8247048,
 '77336': 0.8197934,
 '77338': 0.8230541,
 '77370': 0.7734795,
 '77371': 0.8014289,
 '77372': 0.81999916,
 '77373': 0.83094686,
 '77385': 0.7902851,
 '77386': 0.7838839,
 '77387': 0.7708055,
 '77399': 0.8787127,
 '77401': 0.7829826,
 '77402': 0.79451996,
 '77407': 0.7625052,
 '77412': 0.78503835,
 '77417': 0.76419353,
 '77423': 0.7781334,
 '77424': 0.8485286,
 '77425': 0.84018433,
 '77427': 0.8138017,
 '77431': 0.83277744,
 '77432': 0.82939076,
 '77435': 0.82601804,
 '77469': 0.8000604,
 '77470': 0.82096976,
 '77499': 0.8298972,
 '77520': 0.7946622,
 '77522': 0.78885084,
 '77523': 0.71625,
 '77525': 0.7651155,
 '77600': 0.78001237,
 '77605': 0.79679596,
 '77610': 0.7932125,
 '77615': 0.7988959,
 '77620': 0.74743325,
 '77750': 0.81960124,
 '77761': 0.80489635,
 '77762': 0.76087177,
 '77763': 0.8016348,
 '77767': 0.7662573,
 '77768': 0.7951188,
 '77770': 0.7467696,
 '77771': 0.7533082,
 '77772': 0.7402678,
 '77778': 0.79400593,
 '77789': 0.7805046,
 '77790': 0.80815554,
 '77799': 0.8426111,
 '78012': 0.83278614,
 '78013': 0.785749,
 '78014': 0.8147626,
 '78015': 0.76939327,
 '78016': 0.7907671,
 '78018': 0.75764775,
 '78020': 0.7974188,
 '78070': 0.7764144,
 '78071': 0.7712837,
 '78072': 0.7855982,
 '78075': 0.7950945,
 '78099': 0.8261479,
 '78102': 0.75185037,
 '78103': 0.77356344,
 '78104': 0.7629168,
 '78110': 0.79690456,
 '78111': 0.82140577,
 '78120': 0.79434115,
 '78121': 0.8079514,
 '78122': 0.8052652,
 '78130': 0.799871,
 '78135': 0.8054655,
 '78140': 0.78007245,
 '78185': 0.8144656,
 '78191': 0.8102723,
 '78195': 0.77360404,
 '78199': 0.8052201,
 '78201': 0.7406477,
 '78202': 0.76670104,
 '78205': 0.74362344,
 '78206': 0.77389264,
 '78215': 0.7638264,
 '78216': 0.77235615,
 '78226': 0.80573285,
 '78227': 0.801738,
 '78230': 0.7946787,
 '78231': 0.7763699,
 '78232': 0.7981236,
 '78258': 0.7848225,
 '78261': 0.7748852,
 '78262': 0.7950218,
 '78264': 0.7798594,
 '78265': 0.7649382,
 '78266': 0.7692647,
 '78267': 0.7467283,
 '78268': 0.74449885,
 '78270': 0.78555644,
 '78271': 0.74334013,
 '78272': 0.78833807,
 '78278': 0.7665266,
 '78282': 0.7991843,
 '78290': 0.7864294,
 '78291': 0.80792564,
 '78299': 0.8301676,
 '78300': 0.7508417,
 '78305': 0.79366684,
 '78306': 0.7595593,
 '78315': 0.7648063,
 '78320': 0.7608981,
 '78350': 0.7885686,
 '78351': 0.78673035,
 '78399': 0.8192898,
 '78414': 0.8182985,
 '78428': 0.7378921,
 '78445': 0.80342567,
 '78451': 0.8170659,
 '78452': 0.8048297,
 '78453': 0.8206475,
 '78454': 0.8168276,
 '78456': 0.7615374,
 '78457': 0.7010911,
 '78458': 0.75665945,
 '78459': 0.8182218,
 '78466': 0.80381286,
 '78468': 0.77829206,
 '78469': 0.83287936,
 '78472': 0.81180024,
 '78473': 0.81736565,
 '78481': 0.8121721,
 '78483': 0.82049346,
 '78491': 0.8231242,
 '78492': 0.84717506,
 '78494': 0.8125458,
 '78496': 0.79593325,
 '78499': 0.82686824,
 '78579': 0.7752522,
 '78580': 0.7914146,
 '78582': 0.8008526,
 '78597': 0.79177547,
 '78598': 0.797575,
 '78599': 0.82917845,
 '78600': 0.7577592,
 '78601': 0.7729096,
 '78605': 0.7411175,
 '78606': 0.7650146,
 '78607': 0.8070214,
 '78608': 0.80849576,
 '78609': 0.8130216,
 '78610': 0.8004774,
 '78630': 0.7902464,
 '78635': 0.7888615,
 '78645': 0.810369,
 '78647': 0.7641289,
 '78650': 0.76419824,
 '78660': 0.8020242,
 '78699': 0.83023596,
 '78700': 0.73840845,
 '78701': 0.7579284,
 '78707': 0.7983519,
 '78708': 0.80064833,
 '78709': 0.8159392,
 '78710': 0.7803398,
 '78725': 0.8048401,
 '78730': 0.7865827,
 '78740': 0.77822196,
 '78761': 0.7767312,
 '78799': 0.8217451,
 '78800': 0.7623715,
 '78801': 0.7910248,
 '78802': 0.77567214,
 '78803': 0.78877854,
 '78804': 0.798134,
 '78805': 0.7505923,
 '78806': 0.77472776,
 '78807': 0.7535245,
 '78808': 0.78448164,
 '78811': 0.79194367,
 '78812': 0.7928261,
 '78813': 0.766507,
 '78814': 0.7830989,
 '78815': 0.7875345}

In [36]:
len(overall_code)

20

In [37]:
final_code=[]
for num_text in range(len(overall_code[0])):
    L=[]
    for num_pkl in range(len(overall_code)):
        L.append(overall_code[num_pkl][num_text])
    final_code.append(sorted(L,key=lambda x:x[1])[-1][0])

In [38]:
new_df1["CODE"]=final_code
new_df1.head()

/var/folders/9n/_5t308b12zq7pnycbwd0_tqd6n8q8c/T/ipykernel_30119/2296396196.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df1["CODE"]=final_code

  page line                                               text   CODE
0    9    2  Any expenses related to immunomodulators and i...  32940
1    9    3   Any expenses related to the treatment of slee...  94774
2    9    4    Services and educational programs for handicaps  4305F
3    9    5                                                  A  84630
4    9    6   Injuries or illnesses suffered by the Insured...  59855

In [50]:
new_df1.text.values[4]

' Injuries or illnesses suffered by the Insured Person as a result of military operations of whatever type'

In [51]:
new_df1.CODE.values[4]

'27759'